title: Shirshak Acharya
logo: /assets/img/my_image.png
description: (Computer Vision Researcher in the field of Medical Imaging and Geometry Processing)
# show_downloads: true
theme: jekyll-theme-minimal




